SELECT s.siae_price + s.cachet + SUM(spe.price) + v.price
FROM shows AS s, events AS e, events_service_providers_serve AS spe, venues AS v
WHERE e.show = s.id AND spe.event = e.id AND e.venue = v.id AND e.id = ...
